name: sample-git-env

on:
  push:
    branches:
      - develop
env:
  sample-env-key: ${{secrets.sample}}

jobs:
  gn2-front-build-and-ecrpush:
    runs-on: ubuntu-latest
    timeout-minutes: 300

    steps:
      # - uses: actions/checkout@v2
      - name: docker build test
        run: docker build -t sample-build-git-env .
